### ISSUE TITLE
名不副实

### ISSUE THREAD

**Issue by OctopusLian** [ShanghaiTechVENUS/DLInterview#2]
明明是克隆别人的，结尾处还写大部分内容是自己一个个打上去的。名不副实，请不要做这种骗star的事情。让人啼笑皆非！

**Comment by tonysy** [comment]
- 我们本来就是自己整理自己看的知识库，而且也没有发出去，分明是机器之心自己找到发出去的。
- 我们没有clone别的东西，而是添加的submodule，readme里也说明下边的东西是(From CyC2018)
- 因为忙于科研，我们都半年没更新了，也根本没打算靠这个赚star，被机器之心莫名其妙挖坟，简直无妄之灾。
- 你不喜欢可以不关注，请搞清楚情况再喷。
